2 IMSC feladat hozzáadása meglévő laborokhoz
VIAUAC00/laborok pull request #13
Opened 2022-09-08 20:07 UTC by HLCaptain

Hozzáadtam a 2. és 3. Mobil laborhoz egy-egy Jetpack Compose-ra való átírásukat, mint egy többnyire vezetett bónusz/imsc feladat.

Kijavítottam egy hibát a windows terminálra szánt command-ban, lokális, Windowsról való buildelés esetén. (MKDocs)

2022-09-08 20:22 UTC, tibitoth commented on README.md
> +2. `docker run -it --rm -p 8000:8000 -v "%cd%":/docs squidfunk/mkdocs-material:7.3.6`
Ez most így powershell vagy CMD kompatibilis? A 11. sor powershellre utal.

2022-09-08 20:23 UTC, tibitoth commented on README.md
> +4. Markdown szerkesztése és mentése után automatikusan frissül a weboldal
Izlés kérdése, de a githubos markdown megjelenítő automatikusan növeli a számozást akkor is ha minden 1.-es számot kap

2022-09-08 20:27 UTC, HLCaptain commented on README.md
> +2. `docker run -it --rm -p 8000:8000 -v "%cd%":/docs squidfunk/mkdocs-material:7.3.6`
Igaz, windows terminalt használtam, nem powershellt, javítom!

2022-09-08 22:28 UTC, HLCaptain commented
Hupsz, véletlenül eltávolítottam Eklert és Lászlót a reviewerek közül. Bár azt nem tudom, hogy hogyan, mert az biztos, hogy nem tudom őket se hozzáadni, se eltávolítani a reviewerek közül. Gondolom mivel tőled újrakérvényeztem a reviewt @tibitoth, ezért a többiekét valamiért cancel-ölte a GitHub...

2022-09-10 21:09 UTC, peekler requested changes

2022-09-10 21:09 UTC, peekler commented on README.md
Az alábbiakat egyértelműsítsük a szövegbe, utána mehet fel:
- Ez egy extra feladat, nem iMSC-s feladat, bárki megcsinálhatja.
- Nem jár érte semmilyen bonus, nem része a rendszernek, kísérleti jelleggel készítettük, a JetPack compose terjedése miatt.
- Nem kell feltölteni semmit róla, screenshotot se (tudom hogy teamsen beszéltünk róla, de NE kérjünk most), nem lesz senkinek kapacitása ezt megnézni és bonyolítja a dolgokat, maguknak csinálják meg az érdeklődők nyugodtan
-  Balázs, ha vállalod, odaírhatod az elejére, hogy Te készítetted ezt a Compose-os labort  és Neked küldhetnek direktbe visszajelzéseket.

2022-09-11 08:24 UTC, HLCaptain commented on README.md
Egyértelműsítettem a feladatot:
- jeleztem, hogy tőlem kérhetnek segítséget, valamint hozzám jöhetnek visszajelzésekkel
- kivettem a beadandóra irányuló részeket
- kísérleti jelleggűek a laborok, nem része a pontozási rendszernek

2022-09-11 16:17 UTC, gazdilaci commented on docs/laborok/02-android-ui/index.md
> +A tárgy egyik fiatal laborvezetője által átírásra került ez a labor Jetpack Compose-ra, vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására.
```suggestion
A tárgy egyik fiatal laborvezetője által átírásra került ez a labor Jetpack Compose-ra. Vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására. A labor feladat során sokat kell dolgozni, de célja a Jetpack Compose és modern eszközök, fejlesztési módszertanok népszerűsítése Android platformra. ***Az extra labor kísérleti jelleggel készült és nem része a pontozási rendszernek.***
```

2022-09-11 16:32 UTC, gazdilaci commented on docs/laborok/02-android-ui/index.md
> +A tárgy egyik fiatal laborvezetője által átírásra került ez a labor Jetpack Compose-ra, vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására.
```suggestion
A labor a tárgy egyik fiatal laborvezetője által átírásra került [`Jetpack Compose`](https://developer.android.com/jetpack/compose)-ra. A labor feladat célja a `Jetpack Compose` és a modern eszközök, fejlesztési módszertanok népszerűsítése Android platformra. Az útmutató vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására. Elvégzése extra munkával jár. ***Az extra labor kísérleti jelleggel készült és nem része a pontozási rendszernek.***
```

2022-09-11 16:34 UTC, gazdilaci commented on docs/laborok/03-android-ui-adv/index.md
> +A tárgy egyik fiatal laborvezetője által átírásra került ez a labor Jetpack Compose-ra, vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására.
```suggestion
A labor a tárgy egyik fiatal laborvezetője által átírásra került [`Jetpack Compose`](https://developer.android.com/jetpack/compose)-ra. A labor feladat célja a `Jetpack Compose` és a modern eszközök, fejlesztési módszertanok népszerűsítése Android platformra. Az útmutató vezetetten, hasznos információkkal és tippekkel megtámogatva mutat be egy ideális példát a feladat megoldására. Elvégzése extra munkával jár. ***Az extra labor kísérleti jelleggel készült és nem része a pontozási rendszernek.***
```

2022-09-11 16:38 UTC, gazdilaci reviewed
Az új dolgokba nem nyúlkáltam bele, csak az eredeti feladatsorok utolsó bekezdését írtam át kicsit. 
Amit viszont mindenképpen kéne, hogy a screenshotok valamilyen design kerettel körbe legyenek véve, mert ez így nem túl szép.

2022-09-11 20:12 UTC, HLCaptain commented
@gazdilaci igazából a 2016-os emulátor design nekem személyesen nem annyira tetszik (régimódi), valamint mostanában a modernebb emulátor designok levágnak az app képéből és azért nem hűek, azért gondoltam úgy, hogy csak a plain, Android Studio által kigenerált screeneket rakom oda. Nem hinném, hogy bárki nagy figyelmet fordítana arra, hogy nincs keret a Material Design 3 mellett.

2022-09-12 12:54 UTC, gazdilaci reviewed
OK

2022-09-12 12:55 UTC, gazdilaci approved these changes
OK

2022-09-12 12:58 UTC, merged