List typos fixed
VIAUAC00/laborok pull request #55
Opened 2023-10-31 08:18 UTC by bencemali

2023-11-01 19:42 UTC, tibitoth commented
@bencemali ezek az üres sorok miért kellenek?

2023-11-01 21:58 UTC, gergoradeczki requested changes

2023-11-01 21:58 UTC, gergoradeczki commented on docs/laborok/08-http/index.md
>      * **Táblázatok**
Töröld a `* ` részt a `* **Táblázatok**` sor elején.

2023-11-01 22:04 UTC, gergoradeczki commented
@tibitoth  Ezt a hibát próbálja megoldani:
![image](https://github.com/VIAUAC00/laborok/assets/4851436/f10b03d6-a835-464e-9bd5-525230e819e1)

Viszont feltűnt, hogy a beillesztett táblázat képén el van gépelve Főkök Ference email címe ("fonok"). Ezt még ki tudod javítani @bencemali ?

2023-11-01 23:36 UTC, bencemali commented
Kijavítottam, @gergoradeczki!

2023-11-01 23:49 UTC, gergoradeczki approved these changes

2023-11-01 23:54 UTC, gergoradeczki requested changes
Jaj, most látom, hogy a táblázatnál nem megfelelő html tageket használtált.
Érdemes lehet az itteni sample kódot megnézni: https://www.w3schools.com/tags/tag_thead.asp

2023-11-02 07:09 UTC, bencemali commented
Tényleg. Ezt is kijavítottam, @gergoradeczki!

2023-11-02 09:32 UTC, gincsai approved these changes

2023-11-02 09:32 UTC, merged